services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    image: ${BE_REGISTRY_ADDRESS}:${BE_TAG}
    container_name: base_nest_be
    depends_on:
      database:
        condition: service_healthy
      test-database:
        condition: service_healthy
    ports: [ '8000:8000' ]
    env_file: ./env/.env.backend
    command: sh -c "npm run start:dev"
    volumes:
      - ../:/app
      - /app/node_modules

  database:
    image: mysql:8.0.31
    container_name: db
    restart: unless-stopped
    env_file: ./env/.env.database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 72
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin --disable-log-bin
    volumes:
      - ~/docker-volumes/base_nest/db:/var/lib/mysql
    ports: [ '3306:3306' ]

  test-database:
    image: mysql:8.0.31
    container_name: test-db
    restart: unless-stopped
    env_file: ./env/.env.test-database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 72
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin --disable-log-bin
    volumes:
      - ~/docker-volumes/base_nest/test-db:/var/lib/mysql
    ports: [ '3307:3306' ]